### PR TITLE
Fix #776: Duplicate <title /> tag in the new rendering pipeline

### LINKED ISSUE #776: [Bug] Duplicated Title tag when enabling omitAspNetWebFormsSupport
Prerequisite:
- Fresh Composite C1 6.10 installation with Venus template

Reproduction steps:
- Edit composite.config and set omitAspNetWebFormsSupport to true
- restart C1
- Navigate with browser to page '/Blog/2014/06/30/How-to-view-unpublished-and-unsaved-pages' and view HTML source-code

Expected behaviour:
- HTML title-tag exists exactly once and its content is "How to view unpublished and unsaved pages"

Actual behaviour:
- There are two HTML title-tags
- One contains "Blog" as content and the other contains "How to view unpublished and unsaved pages"

It seems that the head-tag-merge is somehow broken, after setting omitAspNetWebFormsSupport to true. When set to false, this reverts and the title tag is merged again.

### PR DESCRIPTION
**Pull request by napernik**

### CODE REVIEW

File: Composite/Core/WebClient/Renderings/Page/PageRenderer.cs [hunk 1]
```diff
@@ -301,30 +303,43 @@ private static void RemoveDuplicates(XElement head)
...
             foreach (var e in priorityOrderedElements)
             {
-                var id = (string)e.Attribute(XName_Id);
-
-                bool toBeRemoved = CheckForDuplication(uniqueIdValues, id);
+                var tagName = e.Name.LocalName.ToLowerInvariant();
+                bool toBeRemoved;
 
-                if (!toBeRemoved && !e.Nodes().Any())
+                if (tagName == "title")
```
Comment (neexite) [inline Composite/Core/WebClient/Renderings/Page/PageRenderer.cs:317]: Constant for "title"?

**Review by neexite — APPROVED** [review]
